### ISSUE TITLE
How to add service-worker.js file to the root directory

### ISSUE THREAD

**Issue by aqibnawazdev** [goodbarber/plugin_demo#12]
I want to to integrate firebase cloud messaging to my app. It requires services worker file to be in root directory. Is there any way to add file to root directory.?

**Comment by goodbarber** [comment]
Hello,

Unfortunately, it is not possible to access the root directory from a Custom code part of the app. 
I recommend reaching out to support to explore available options and see if there’s a solution for integrating Firebase Cloud Messaging into your app.

If you have any other questions, just let us know!

Cheers,
GoodBarber

**Comment by aqibnawazdev** [comment]
Thank you..!!
